apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-addon
  template:
    metadata:
      labels:
        app: metrics-addon
    spec:
      containers:
        - name: addon
          image: williamkoller/metrics-addon:latest
          ports:
            - containerPort: 8080
